---
- name: ansible facts demo with ansible variables in new form
  hosts: all

  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    ipv4: "{{ ansible_facts['default_ipv4']['address'] }}"
    distro: "{{ ansible_facts['distribution'] }}"
    version: "{{ ansible_facts['distribution_version'] }}"
    mem: "{{ ansible_facts['memtotal_mb'] }}"
    cpus: "{{ ansible_facts['processor_vcpus'] }}"
    arch: "{{ ansible_facts['architecture'] }}"

  tasks:
    - name: print out variables
      debug:
        msg: "{{ distro }} {{ version }} ({{ arch }}) – {{ hostname }} - IP {{ ipv4 }} - RAM {{ mem }}MB - CPUs {{ cpus }}"
...
