---
- name: ansible facts demo with ansible variables in new form
  hosts: all

  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    ipv4: "{{ ansible_facts['all_ipv4_addresses'] }}"
    distro: "{{ ansible_facts['distribution'] }}"
    version: "{{ ansible_facts['distribution_version'] }}"
    mem: "{{ ansible_facts['memtotal_mb'] }}"
    cpus: "{{ ansible_facts['processor_vcpus'] }}"
    arch: "{{ ansible_facts['architecture'] }}"

  tasks:
    - name: print out variables
      debug:
        msg: "{{ distro }} - {{ version }} - {{ arch }} – {{ hostname }} - {{ ipv4 }} - RAM {{ mem }}MB - CPUs {{ cpus }}"
...
