---
- name: Install packages
  hosts: rpm,apt
  become: yes

  vars:
    packages:
      - tree
      - nmap
      - telnet
      - htop
      - neofetch
      - vim
    distro: "{{ ansible_facts['distribution'] }}"
    version: "{{ ansible_facts['distribution_major_version'] }}"
    arc: "{{ ansible_facts['architecture'] }}"

  tasks:

    - name: Messages for packages installation
      debug:
        msg: "Installing {{ packages }}"

    - name: Install EPEL 9
      dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present
        disable_gpg_check: yes
      when:
        - distro == "RedHat"
        - version == "9"

    - name: Install EPEL 8
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present
        disable_gpg_check: yes
      when:
        - distro == "RedHat"
        - version == "8"

    - name: RPM-based packages with DNF
      dnf:
        name: "{{ packages }}"
        state: latest
      when:
        - distro == "RedHat" or distro == "Fedora"

    - name: APT-based packages
      apt:
        name: "{{ packages }}"
        state: latest
      when:
        - distro == "Ubuntu" or distro == "Debian"

    - name: Intall insights-client for RHEL-based distro
      dnf:
        name: insights-client
        state: latest
      when:
        - distro == "RedHat"

    - name: Register the insights client for RHEL-based distro
      command:
        cmd: insights-client --register
      when:
        - distro == "RedHat"
...
