---
- name: Install packages
  hosts: localhost

  vars:
    packages:
      - tree
      - nmap
      - telnet
      - htop
      - neofetch
      - vim

  tasks:

    - name: Messages for packages installation
      debug:
        msg: "Installing {{ packages }}"

    - name: Install packages
      dnf:
        name: "{{ packages }}"
        state: latest
...
