---
- name: sudo visudo
  hosts: all
  become: yes

  tasks:

  - name: Create sudoer file for parallels
    copy:
      content: 'parallels ALL=(ALL) NOPASSWD: ALL'
      dest: /etc/sudoers.d/parallels
      owner: root
      group: root
      mode: ug+rwX,o=
      force: yes
      validate: visudo -cf %s
...
