---
- name: sudoers
  hosts: rpm,apt
  become: yes

  tasks:

  - name: Create sudoers file for ansible
    copy:
      content: 'ansible ALL=(ALL) NOPASSWD: ALL'
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: ug+rwX,o=
      force: yes
      validate: visudo -cf %s
...
