---
- name: Update Packages
  hosts: all
  become: yes

  vars:
    distro: "{{ ansible_facts['distribution'] }}"
    version: "{{ ansible_facts['distribution_major_version'] }}"

  tasks:

    - name: Messages for packages installation
      debug:
        msg: "Update all packages"

    - name: RPM-based distros with DNF
      dnf:
        name: '*'
        state: latest
      when:
        - distro == "RedHat"
        - version == "8" or version == "9"

    - name: RPM-based distros with YUM for CentOS legacy systems
      yum:
        name: '*'
        state: latest
      when:
        - distro == "CentOS" or distro == "RedHat"
        - version == "7"

    - name: APT-based distros
      apt:
        name: '*'
        state: latest
      when:
        - distro == "Ubuntu"
...
