---
- name: Update Packages
  hosts: rpm
  become: yes

  tasks:

    - name: Messages for packages installation
      debug:
        msg: "Update all packages"

    - name: RPM-based distros with DNF
      dnf:
        name: '*'
        state: latest
...
