---
- name: Install packages
  hosts: rpm,apt

  tasks:

    - name: Messages for packages installation
      debug:
        msg: "Update all packages"

    - name: RPM
      yum:
        name: '*'
        state: latest
      when: '"rpm" in group_names'

    - name: APT
      apt:
        name: '*'
        state: latest
      when: '"apt" in group_names'
...
